### PR TITLE
fix: Don't register sched events on blocking pool threads

### LINKED ISSUE #314: protect from file descriptor exhaustion when subscribing to perf events
Right now, sampling scheduling events opens a separate fd for each thread (which can exhaust fds). We need a hard limit to protect fds. A reasonable approach is only enabling sampling when we _know_ a thread has become a Tokio worker thread

### PR DESCRIPTION
**Pull request by rcoh**
fixes #314 

The combination of two bugs:
1. perf file descriptors were never closed
2. blocking threads opened their own perf fd

Caused a leak of perf file descriptors over time

### CODE REVIEW

File: dial9-tokio-telemetry/tests/sched_profiler_fd_leak.rs [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+        let mut handles = Vec::new();
+        for _ in 0..num_blocking_tasks {
+            handles.push(tokio::task::spawn_blocking(|| {
+                std::thread::sleep(Duration::from_millis(50));
+            }));
+        }
+        for h in handles {
+            h.await.unwrap();
+        }
+        // Wait for threads to exit and on_thread_stop to fire.
```
Comment (jlizen) [inline dial9-tokio-telemetry/tests/sched_profiler_fd_leak.rs:76]: nit: this is a bit misleading since we never open fds in the first place for blocking threads, so there is no need to wait on cleanup.

File: dial9-tokio-telemetry/src/telemetry/recorder/mod.rs
Comment (jlizen) [inline dial9-tokio-telemetry/src/telemetry/recorder/mod.rs:258]: nit: this is taking the lock to tear down blocking threads that no longer need cleanup. Not sure if it is worth adding a `runtime_context::is_sched_tracked()` to check the thread-local state to avoid that. Probably not :)

**Review by jlizen — APPROVED** [review]

File: dial9-tokio-telemetry/src/telemetry/recorder/mod.rs [hunk 2]
```diff
@@ -241,12 +241,10 @@ fn register_hooks(
...
                     .insert(tid, crate::telemetry::events::ThreadRole::Blocking);
-                if let Ok(mut prof) = s_start.sched_profiler.lock()
-                    && let Some(ref mut p) = *prof
-                {
-                    // Register the current thread for sched event sampling.
-                    let _ = p.track_current_thread();
-                }
+                // Sched event sampling is deferred to register_tid_if_needed(),
+                // which runs only for worker threads on their first poll/park.
+                // This avoids opening perf fds for blocking pool threads.
```
Comment (jlizen) [inline dial9-tokio-telemetry/src/telemetry/recorder/mod.rs:246]: Just to note, we still do have coverage of blocking threads via the cpu profiler's inherit approach. Was my main question while reading this.
