### PR TITLE
fix: capture blocking thread tid directly instead of guessing by name

### LINKED ISSUE #101: Flaky test: `thread_name_attribution_for_external_and_blocking_threads`
## Description

`cpu_sample_clock_alignment::thread_name_attribution_for_external_and_blocking_threads` is flaky in CI. It asserts that the CPU profiler collected at least one sample from a `spawn_blocking` thread, but sampling is probabilistic and the thread may not be sampled during the short test window.

## Example failure

https://github.com/dial9-rs/dial9-tokio-telemetry/actions/runs/23274115410/job/67673271437?pr=100

```
CPU samples for ext thread (tid=11418): 397
CPU samples for blocking thread (tid=11415): 0

thread 'thread_name_attribution_for_external_and_blocking_threads' panicked at:
expected CPU samples for blocking thread tid=11415
```

The external thread got 397 samples, but the blocking thread got 0. The test uses a bare `assert!(!blocking_samples.is_empty())` with no retry or minimum burn time for the blocking thread.

## Possible fixes

- Increase the CPU burn duration on the blocking thread so it's more likely to be sampled
- Retry the assertion a few times with a short sleep
- Mark the test with `#[ignore]` in CI and run it separately with retries

### PR DESCRIPTION
**Pull request by rcoh**
The test was flaky because it identified the blocking thread by finding the first CpuSample with a thread name starting with "test-traced-run".  Blocking pool threads share the same prefix with workers so sometimes we picked a worker. When find() picked a worker thread, the subsequent filter for WorkerId::BLOCKING on that tid returned 0 samples.

Fix: capture the tid from inside the spawn_blocking closure using nix::unistd::gettid(), then use that known tid for assertions.

10m stress test passed: https://github.com/dial9-rs/dial9-tokio-telemetry/actions/runs/23348846028

fixes #101

### CODE REVIEW

File: dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs [hunk 1]
```diff
@@ -284,19 +284,21 @@ fn thread_name_attribution_for_external_and_blocking_threads() {
     // ── spawn_blocking — also exits before flush ─────────────────────────
     let blocking_handle = runtime.spawn(async {
         tokio::task::spawn_blocking(|| burn_cpu(Duration::from_millis(400)));
-        tokio::task::spawn_blocking(|| burn_cpu(Duration::from_millis(400)))
-            .await
-            .unwrap();
+        tokio::task::spawn_blocking(|| {
+            let tid = nix::unistd::gettid().as_raw() as u32;
```
Comment (jlizen) [inline dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs]: this would probably benefit from an explanatory comment about the cast

File: dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs [hunk 2]
```diff
@@ -330,18 +332,15 @@ fn thread_name_attribution_for_external_and_blocking_threads() {
...
-        .iter()
-        .find(|(_, name)| name.starts_with("test-traced-run"));
+    // ── Verify the blocking thread has the expected name ────────────────
+    let blocking_name = unique_defs.get(&blocking_tid);
+    eprintln!("Blocking thread tid={blocking_tid}, name={blocking_name:?}");
     assert!(
-        blocking_def.is_some(),
-        "expected CpuSample with thread_name starting with 'test-traced-run', got: {unique_defs:?}"
+        blocking_name.is_some_and(|n| n.starts_with("test-traced-run")),
+        "expected blocking thread name starting with 'test-traced-run', got: {blocking_name:?}"
```
Comment (jlizen) [inline dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs]: consider also including `{unique_defs:?}` in this message in case `blocking_name` is `None`

File: dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs [hunk 3]
```diff
@@ -330,18 +332,15 @@ fn thread_name_attribution_for_external_and_blocking_threads() {
...
     );
-    let blocking_tid = blocking_def.unwrap().0;
 
-    // ── Verify CpuSamples exist for both tids with UNKNOWN_WORKER ────────
+    // ── Verify CpuSamples exist for both tids ────────────────────────────
```
Comment (jlizen) [inline dial9-tokio-telemetry/tests/cpu_sample_clock_alignment.rs]: *with expected worker IDs?
